---
title: "Final Write UP"
output: pdf_document
date: "2024-02-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Names**

Maggie Lyman Github: maggie-lyman
Max Wagner Github: maxwellwikstrom

**Writeup**

In May 2021, Chicago passed the Additional Dwelling Unit (ADU) Ordinance. The legislation streamlined zoning requirements for basement and attic apartment conversion projects and legalized the construction of backyard coach houses. The ordinance was enacted in five pilot zones (North, Northwest, South, West, and Southwest) dispersed throughout the city. 

The ADU Ordinance sets some restrictions by zone. In the West, South, and Southwest zones, only two ADU permits can be issued per block per year. In these zones, buildings with one to three units must also be owner-occupied to add a basement/attic unit. Conversely, in the North and Northwest zones, homeowners can build coach houses on vacant lots before a primary residence is built. There are additional stipulations across all zones to increase affordability. For properties with two or more new ADUs, rent must be set at 60% area median income (AMI) for 30 years for every other additional unit added to the property. 

The program was designed to provide affordable housing, increase density in popular neighborhoods, provide rental units in neighborhoods that are primarily single-family homes, and provide additional income for homeowners and landlords. Mayor Lori Lightfoot, in a press release celebrating the legislation, wrote:

“By increasing affordable housing opportunities for renters, while also helping property owners deal with the financial demands of their buildings, these ADUs will be a major step forward in our ongoing work to support our most vulnerable residents.”

The goal of our research project is to test Mayor Lightfoot’s hypothesis that the ADU Ordinance would serve Chicago’s most vulnerable residents. Now that the program has been in effect for over two years, we want to evaluate it by asking the following research questions:

  1. How effective has the ADU Ordinance been at generating affordable housing – either legally restricted affordable housing or “naturally” affordable housing?
  2. How have the restrictions in the South, West and Southwest zones impacted the number of ADUs being built?
  3. What is the public perception of ADUs as affordable housing?

Our analysis includes data on ADU permit applications, Chicago income and rent, and Chicago shapefiles by census tract, ADU pilot zone, and neighborhood. To obtain data on how the general public felt about the ordinance, we collected text data from the Chicago subreddit thread on ADUs. Most program analysis is at the zone level. However, understanding that most audiences are familiar with Chicago neighborhoods rather than census tract areas or ADU pilot zones, we have an interactive plot that presents ADU permit information by neighborhoods. 

Our biggest challenge was merging income and rent data with neighborhood and zone shapefiles. We used the census tract shape file as an intermediary to add geometric information to the median gross rent and median income of different tract areas. To merge with neighborhood and zone boundaries, weighted averages of gross rent and median income were calculated using census tract population data. Some census tracts only partially fall in an ADU zone. Dummy variables were created for any census tract where at least 50% of its area is in the ADU zone. Only those tracts were included in the weighted average.

The choropleth plots of ADU permits by average gross rent and ADU denials by zone show the inverse of places with high average rent receiving more permits and less denials. While median income was calculated in the code and used in one of our Shiny plots, we were unable to communicate the median income in our choropleths in a clean way. While those familiar with Chicago can discern that more permits on the north side and more denials on the southwest side indicate inequities in policy implementation by income, this information is not clear for viewers who are unfamiliar with Chicago. 

The static plot file also includes a count of the number of affordable vs market rate ADUs. While the original ordinance was praised for increasing affordable housing, we find that the number of affordable units created is quite small. 

The first shiny app shows the number of permit applications and approvals by month for each neighborhood within a pilot zone. Users can select a neighborhood and the plotly graph will update. There are additional tabs for the weighted median gross rent and weighted median income for the selected neighborhood.

Our OLS regression model evaluates the relationship between approved ADU permits and median gross rent and median income. There is a positive, statistically significant relationship between median gross rent and median income and the number of ADU permits issued. The regression model is plotted.

The second shiny app analyzes Reddit comments by sentiment. The first page is a bar graph analyzing comments by NRC sentiments. Summary statistics using afinn sentiments are displayed below. The overall sentiment skews positive, but negative push back is evident. The second page includes dependency graphs with the four most common words found on Reddit thread: Chicago, City, Housing, and Ordinance. Users can select a most-common-word and the dependency graph will update. Each dependency graph includes the word “affordable” despite the affordable units comprising a very small subset of ADUs. 

Our analysis shows that there is a strong positive correlation between the number of ADU permits issued and the median gross rent of an area. Though the five pilot zones are scattered across Chicago, most ADUs are built in the North and Northwest zones. A very small percentage of units are legally restricted as affordable at the 60% AMI level, meaning most units are market-rate. Given the relatively high market rent in the North and Northwest zones, it is questionable whether ADUs are truly helping to deliver affordable housing opportunities to Chicago’s most vulnerable residents.

The restrictions in the legislation for homeowners in the South, West and Southwest sides may provide one explanation for the unequal distribution of ADU permits. Our analysis shows that more ADU permit applications are denied in those zones, potentially because of the strict rules put in place. Since the median gross rent is lower in the South, West and Southwest zones, new ADUs in these areas would likely generate more “naturally” affordable housing.

Lastly, we find that public perception of the ADU Ordinance, as measured by the Reddit thread, was relatively positive. However, the affordability aspect of the program was a significant part of the conversation. This could mean that supporters of the legislation have been led to believe that the number of affordable units generated would be higher than what our analysis found. There could be a mismatch between public perception of the program and reality.

Future research on this topic could explore the impact of new ADUs on overall rent in a community. One hypothesis by proponents of ADUs is that the additional supply of housing reduces rents in the long-run. It would be interesting to assess how rents have changed in the five pilot zones over time, though there would be limitations to assigning causality.

In addition, we would like to assess the rent burden in each ADU zone. Rent burden takes median income and median gross rent to determine where renters are the most cost-burdened. This could be another interesting metric to use to make comparisons across zones. 

Another variable that could be added to our analysis is the number of total possible ADUs in each zone. One limitation to our analysis is that there may be a difference in the number of units that could ever be zoned. If there’s more possible units in the North and Northwest zones, that could be a reason for the inequality across zones.

Lastly, future research could be done on how Chicagoans perceive the effectiveness of the ADU Ordinance. Since Reddit is only one small part of the overall discourse, it could be interesting to analyze news articles to assess sentiment. In addition, future research could be done on the text of the ADU Ordinance to count the number of times “affordability” is referenced.


